export default ACTIONS = {
    PLAY: 'PLAY',
    PAUSE: 'PAUSE',
    REWIND: 'REWIND',
    PREVIOUS: 'PREVIOUS',
    FORWARD: 'FORWARD',
    NEXT: 'NEXT',
    REPEAT: 'REPEAT',
    SHUFFLE: 'SHUFFLE',
    SET_TRACK: 'SET_TRACK',
    SET_PLAYLIST: 'SET_PLAYLIST',
    MUTE: 'MUTE',
    INCREASE_VOLUME: 'INCREASE_VOLUME',
    DECREASE_VOLUME: 'DECREASE_VOLUME'
}